// Package pins holds the Target Chrome and everything that rolls with it: the
// Chrome for Testing Stable version wand is aligned to and its Chromium main
// branch position, the Protocol roll the protocol layer is generated from, the
// Companion Chromium trunk build, and the SHA-256 of every Managed browser
// archive the launcher may download.
//
// The package imports nothing, so the launcher and the protocol generator can
// both read it, and the release workflow reads it through the printer at
// internal/tools/print-pins rather than by parsing source. Only the Roll
// rewrites it: pins.go is generated by lib/launcher/pins/generate once per
// Chrome stable milestone, and "go run ./lib/launcher/pins/generate -check"
// verifies that the committed file is what the Roll would write and that the
// Protocol roll still derives from the branch position (ADR-0004, ADR-0005,
// ADR-0009).
package pins
