// Code generated by lib/launcher/pins/generate; DO NOT EDIT.

package pins

// ChromeVersion is the Target Chrome: the Chrome for Testing Stable version
// the protocol layer is generated for and the launcher's default Managed
// browser is pinned to.
const ChromeVersion = "152.0.7977.82"

// ChromePosition is the Chromium main branch position the Target Chrome
// branched from, as Chrome for Testing reports it.
const ChromePosition = 1669021

// ProtocolRoll is the Protocol roll: the devtools-protocol revision the
// protocol layer is generated from, tag v0.0.<ProtocolRoll> of
// ChromeDevTools/devtools-protocol, the largest roll not above ChromePosition.
const ProtocolRoll = 1666840

// ChromiumPosition is the Companion Chromium: the newest Chromium trunk build
// at or below ChromePosition whose archive exists for every prefix in
// ChromiumSHA256.
const ChromiumPosition = 1668623

// ChromeSHA256 is the SHA-256, as lower-case hex, of each Chrome for Testing
// archive of the Target Chrome, keyed by binary and then by Chrome for Testing
// platform. The Roll computed every value from the archive it downloaded from
// Google's bucket; a platform without an entry has no archive for this
// version.
var ChromeSHA256 = map[string]map[string]string{
	"chrome": {
		"linux64":   "0704631fb3e4f741092e08f55272f90abc3e307f991f05f332924364415b02e0",
		"mac-arm64": "6a12c6e76fcd0dc44accc8d28e93caa44ead57b71b8e0cac891bc3152a709790",
		"mac-x64":   "468498b1b95e6114bae4880ef0f9c884c7653d120ecbde37885e1ba923c31526",
		"win32":     "c59ab3ab775933c9c6aa4eac7cad19936d01b7ffccae331b618910626875eafa",
		"win64":     "460016c1ddba882bf253445175ab240dd947fa349bd720daeb0e311c17e74540",
	},
	"chrome-headless-shell": {
		"linux64":   "0ca12ea26b502a83e32db334a17883c315348845efc071d908de7a6d94a97eff",
		"mac-arm64": "1615f063c894aa824fd55c89f8f05e9904f63cce0c95d0cbce7394d77884fba5",
		"mac-x64":   "c903707292c6aaed7c6e572c0bb5e6645454e45d9e0e6db27e876b18e9165f31",
		"win32":     "c8c6db718c3bd8470735b1434cecc651a26f8a6d4424fb0eb63f415d6653ff5a",
		"win64":     "86fb1fa7fbbda65f6f1572062c358803e61a6e6d9489e6619b37a61d609fa845",
	},
}

// ChromiumSHA256 is the SHA-256, as lower-case hex, of the Companion Chromium
// archive under each Chromium snapshots bucket prefix.
var ChromiumSHA256 = map[string]string{
	"Linux_x64": "790e8ebbddd97546b49a721e8251fdd06684dcce82bd1c0925b67904aab6c74c",
	"Mac":       "347600058d49e4cc5a13cd433eb32854cc9022a06add5ed621c6292131c8ee13",
	"Mac_Arm":   "5c28212769d3ac9b3c2053ee8c2e94e50994d3a4833ae4ed864d73c325284c6b",
	"Win":       "f313265b99f4c709078d39797615cb0bd79c286b86298172b800cec0b3098e91",
	"Win_x64":   "3f3a1369e66ea858105dbc6855ceefe0ebf97402c7782711610dc6393b283ea9",
}
