package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
)

// render is the source of lib/launcher/pins/pins.go for p, gofmt-formatted
// with every table in key order, so the same pins always give the same bytes.
func render(p Pins) ([]byte, error) {
	b := &bytes.Buffer{}

	fmt.Fprintf(b, `// Code generated by lib/launcher/pins/generate; DO NOT EDIT.

package pins

// ChromeVersion is the Target Chrome: the Chrome for Testing Stable version
// the protocol layer is generated for and the launcher's default Managed
// browser is pinned to.
const ChromeVersion = %q

// ChromePosition is the Chromium main branch position the Target Chrome
// branched from, as Chrome for Testing reports it.
const ChromePosition = %d

// ProtocolRoll is the Protocol roll: the devtools-protocol revision the
// protocol layer is generated from, tag v0.0.<ProtocolRoll> of
// ChromeDevTools/devtools-protocol, the largest roll not above ChromePosition.
const ProtocolRoll = %d

// ChromiumPosition is the Companion Chromium: the newest Chromium trunk build
// at or below ChromePosition whose archive exists for every prefix in
// ChromiumSHA256.
const ChromiumPosition = %d

// ChromeSHA256 is the SHA-256, as lower-case hex, of each Chrome for Testing
// archive of the Target Chrome, keyed by binary and then by Chrome for Testing
// platform. The Roll computed every value from the archive it downloaded from
// Google's bucket; a platform without an entry has no archive for this
// version.
var ChromeSHA256 = map[string]map[string]string{
`, p.ChromeVersion, p.ChromePosition, p.ProtocolRoll, p.ChromiumPosition)

	binaries := make([]string, 0, len(p.ChromeSHA256))
	for binary := range p.ChromeSHA256 {
		binaries = append(binaries, binary)
	}
	sort.Strings(binaries)
	for _, binary := range binaries {
		fmt.Fprintf(b, "\t%q: {\n", binary)
		for _, platform := range sortedKeys(p.ChromeSHA256[binary]) {
			fmt.Fprintf(b, "\t\t%q: %q,\n", platform, p.ChromeSHA256[binary][platform])
		}
		fmt.Fprintf(b, "\t},\n")
	}

	fmt.Fprintf(b, `}

// ChromiumSHA256 is the SHA-256, as lower-case hex, of the Companion Chromium
// archive under each Chromium snapshots bucket prefix.
var ChromiumSHA256 = map[string]string{
`)
	for _, prefix := range sortedKeys(p.ChromiumSHA256) {
		fmt.Fprintf(b, "\t%q: %q,\n", prefix, p.ChromiumSHA256[prefix])
	}
	fmt.Fprintf(b, "}\n")

	return format.Source(b.Bytes())
}
