// Package main ...
package main

import (
	"path/filepath"

	"github.com/headlesslab/wand/internal/devutil"
	"github.com/headlesslab/wand/lib/utils"
)

var slash = filepath.FromSlash

func main() {
	build := devutil.S(`// Package assets is generated by "internal/assets/generate"
package assets

// MousePointer for wand.
const MousePointer = {{.mousePointer}}

// Monitor for wand.
const Monitor = {{.monitor}}

// MonitorPage for wand.
const MonitorPage = {{.monitorPage}}
`,
		"mousePointer", get("../../fixtures/mouse-pointer.svg"),
		"monitor", get("monitor.html"),
		"monitorPage", get("monitor-page.html"),
	)

	utils.E(utils.OutputFile(slash("internal/assets/assets.go"), build))
}

func get(path string) string {
	code, err := devutil.ReadString(slash("internal/assets/" + path))
	utils.E(err)
	return devutil.EscapeGoString(code)
}
