// Package main generates lib/proto from ChromeDevTools/devtools-protocol at
// the Protocol roll of lib/launcher/pins, with no browser involved
// (ADR-0004):
//
//	go run ./lib/proto/generate                # tag v0.0.<pins.ProtocolRoll> from GitHub
//	go run ./lib/proto/generate -schema <dir>  # a checkout of that tag, for offline use
//
// The generator downloads json/browser_protocol.json and
// json/js_protocol.json of the tag and merges them, the same content a
// browser serves at /json/protocol; applies upstream's patches; restores
// []byte for the fields whose type the JSON lowered to string, from the
// base64 marker in their description and from the hand-kept binaryFields
// list; and refuses to write anything when the number of []byte fields
// differs from the binary occurrences in the tag's PDL files. It then
// replaces every generated file under lib/proto (the a_ files are
// hand-written and stay), formats them with the pinned golangci-lint, and
// prints a summary of the removed, renamed and newly deprecated Go
// identifiers, also written to tmp/proto-summary.md, for the Roll pull
// request and the release notes.
//
// Deprecated entities and fields carry Go's Deprecated paragraph;
// experimental ones are generated like any other; entities the roll removed
// disappear with no stub. The Protocol roll is written beside the protocol
// version constant, so a test can hold lib/proto to the pins.
//
// Known limitation, kept on purpose (spec #33, section 4; rod #1196): an
// optional boolean is a plain bool with omitempty, so a false that differs
// from Chrome's default is never sent. Changing the field type is API
// modernization, outside the baseline release.
package main

import (
	"context"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"time"

	"github.com/headlesslab/lazyjson"
	"github.com/headlesslab/wand/internal/devutil"
	"github.com/headlesslab/wand/lib/launcher/pins"
	"github.com/headlesslab/wand/lib/utils"
)

const generatedBy = `// This file is generated by "./lib/proto/generate"`

// downloadTimeout bounds each of the few requests to GitHub; the largest
// file of a tag is under 2 MB.
const downloadTimeout = 2 * time.Minute

func main() {
	opts, err := parseArgs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		usage(os.Stderr)
		os.Exit(2)
	}

	os.Exit(run(opts))
}

type options struct {
	schema string
}

func parseArgs(args []string) (options, error) {
	var opts options
	fs := flagSet(&opts)
	if err := fs.Parse(args); err != nil {
		return options{}, err
	}
	if fs.NArg() > 0 {
		return options{}, fmt.Errorf("unexpected argument %q", fs.Arg(0))
	}
	return opts, nil
}

// flagSet declares the flags on opts. usage prints the same set, so every
// flag is described once.
func flagSet(opts *options) *flag.FlagSet {
	fs := flag.NewFlagSet("proto", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	fs.StringVar(&opts.schema, "schema", "",
		"a checkout of ChromeDevTools/devtools-protocol at tag v0.0.<ProtocolRoll>, read instead of GitHub")
	return fs
}

func usage(w io.Writer) {
	_, _ = fmt.Fprintln(w, "usage: go run ./lib/proto/generate [-schema <dir>]")
	fs := flagSet(&options{})
	fs.SetOutput(w)
	fs.PrintDefaults()
}

// run does the work and returns the exit status, so that main's os.Exit
// happens after the signal handler is released.
func run(opts options) int {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	src := remoteSource(&http.Client{Timeout: downloadTimeout}, protocolRaw, pins.ProtocolRoll)
	if opts.schema != "" {
		var err error
		if src, err = localSource(opts.schema, pins.ProtocolRoll); err != nil {
			return fail(err)
		}
	}

	g := &generator{
		root:   ".",
		src:    src,
		roll:   pins.ProtocolRoll,
		binary: binaryFields,
		format: true,
		log:    log.New(os.Stderr, "[proto] ", log.Ltime),
	}
	summary, err := g.generate(ctx)
	if err != nil {
		return fail(err)
	}
	fmt.Print(summary)

	return 0
}

func fail(err error) int {
	fmt.Fprintln(os.Stderr, "proto:", err)
	return 1
}

// generator writes lib/proto for one roll.
type generator struct {
	root   string // the module root, where lib/proto and tmp are
	src    source
	roll   int
	binary []binaryField
	format bool // run the pinned golangci-lint formatters on the output
	log    *log.Logger
}

// generate reads the roll, checks it, rewrites lib/proto and returns the
// summary of what changed. Nothing is written when the schema, the patches
// or the binary count fail.
func (g *generator) generate(ctx context.Context) (string, error) {
	dir := filepath.Join(g.root, "lib", "proto")

	before, err := readSymbols(dir)
	if err != nil {
		return "", err
	}

	g.log.Printf("reading %s", g.src)
	schema, err := g.src.schema(ctx)
	if err != nil {
		return "", err
	}
	if err := utils.OutputFile(filepath.Join(g.root, "tmp", "proto.json"), schema.JSON("", "  ")); err != nil {
		return "", err
	}

	domains, err := parse(schema, g.binary)
	if err != nil {
		return "", err
	}

	pdl, err := g.src.pdl(ctx)
	if err != nil {
		return "", err
	}
	if err := checkBinary(pdl, domains); err != nil {
		return "", err
	}

	files := render(domains, schema, g.roll)
	if err := writeFiles(dir, files); err != nil {
		return "", err
	}
	g.log.Printf("wrote %d files to %s", len(files), dir)

	if g.format {
		devutil.GoTool(devutil.GolangciLint, "fmt", "./"+filepath.ToSlash(dir))
	}

	after, err := readSymbols(dir)
	if err != nil {
		return "", err
	}
	summary := summarize(before, after).markdown(g.roll)
	if err := utils.OutputFile(filepath.Join(g.root, "tmp", "proto-summary.md"), summary); err != nil {
		return "", err
	}

	return summary, nil
}

// writeFiles replaces the generated files of dir with files, each first
// passed through gofmt, which also proves it is valid Go; nothing is removed
// when one is not.
func writeFiles(dir string, files map[string]string) error {
	for name, code := range files {
		formatted, err := format.Source([]byte(code))
		if err != nil {
			return fmt.Errorf("generated %s is not valid Go: %w", name, err)
		}
		files[name] = string(formatted)
	}

	if err := cleanup(dir); err != nil {
		return err
	}
	for name, code := range files {
		if err := utils.OutputFile(filepath.Join(dir, name), code); err != nil {
			return err
		}
	}
	return nil
}

// checkBinary fails when the number of []byte fields the definitions carry
// differs from the number of binary occurrences in the PDL, so a marker-less
// field the hand-kept list lacks, or an entry the roll removed, stops the
// run before anything is written (ADR-0004). It is a count: the two lists
// name things differently, and a count is what the spec asks for.
func checkBinary(pdl []pdlFile, domains []*domain) error {
	occurrences := binaryOccurrences(pdl)
	fields := byteFields(domains)
	if len(occurrences) == len(fields) {
		return nil
	}
	return fmt.Errorf("the PDL files use binary %d times but the generated code would have %d []byte fields; "+
		"a field without a description carries no marker and needs an entry in binaryFields "+
		"(lib/proto/generate/patch.go)\nbinary in the PDL:\n  %s\n[]byte in Go:\n  %s",
		len(occurrences), len(fields), strings.Join(occurrences, "\n  "), strings.Join(fields, "\n  "))
}

// render is every generated file of lib/proto by name: one file per domain,
// definitions.go with the version, the roll and the type table, and the
// generated tests.
func render(domains []*domain, schema lazyjson.JSON, roll int) map[string]string {
	files := map[string]string{}

	definitions := generatedBy + devutil.S(`

		package proto

		import (
			"reflect"
		)

		// Version of the Chrome DevTools Protocol.
		const Version = "v{{.major}}.{{.minor}}"

		// ProtocolRoll is the Protocol roll this package is generated from: tag
		// v0.0.<ProtocolRoll> of ChromeDevTools/devtools-protocol, the largest
		// roll not above the Target Chrome's branch position
		// (lib/launcher/pins).
		const ProtocolRoll = {{.roll}}

		var types = map[string]reflect.Type{
	`, "major", schema.Get("version.major").Str(), "minor", schema.Get("version.minor").Str(), "roll", roll)

	tests := generatedBy + `

		package proto_test

		import (
			"github.com/headlesslab/wand/lib/proto"
		)
	`

	for _, domain := range domains {
		body := fmt.Sprintf("/*\n\n%s\n\n", domain.name)
		if domain.description != "" {
			body += domain.description + "\n\n"
		}
		body += "*/\n\n"

		for _, definition := range domain.definitions {
			if definition.skip {
				continue
			}

			body += definition.format()
			tests += definition.formatTests()

			if definition.originName != "" {
				definitions += devutil.S(`
					"{{.name}}": reflect.TypeOf({{.type}}{}),`,
					"name", definition.domain.name+"."+definition.originName,
					"type", definition.name,
				)
			}
		}

		code := generatedBy + "\n\npackage proto\n\n"
		if usesLazyjson(domain) {
			code += "import (\n\t\"github.com/headlesslab/lazyjson\"\n)\n\n"
		}
		files[toSnakeCase(domain.name)+".go"] = code + body
	}

	definitions += "\n}\n"
	files["definitions.go"] = definitions
	files["definitions_test.go"] = tests

	return files
}

func (d *definition) comment() string {
	comment := d.description

	if comment == "<nil>" {
		comment = "..."
	}

	if d.optional {
		comment = "(optional) " + comment
	}
	if d.experimental {
		comment = "(experimental) " + comment
	}
	if d.deprecated() {
		comment = "(deprecated) " + comment
	}

	name := symbol(d.name)

	if !strings.HasPrefix(strings.TrimSpace(comment), name) {
		comment = name + " " + comment
	}

	return commentLines(withPeriod(comment) + d.deprecatedParagraph())
}

// deprecatedParagraph is the Go Deprecated paragraph to append to a doc
// comment, or nothing.
func (d *definition) deprecatedParagraph() string {
	if !d.deprecated() {
		return ""
	}
	return "\n\nDeprecated: " + d.deprecation + "."
}

// withPeriod ends a description with a period when the protocol left it
// without one, as Go doc convention and the godot linter want.
func withPeriod(s string) string {
	s = strings.TrimRight(s, " \t\n")
	if strings.HasSuffix(s, ".") || strings.HasSuffix(s, "!") || strings.HasSuffix(s, "?") {
		return s
	}
	return s + "."
}

// commentLines turns text into a line comment, a bare // on blank lines so
// that no line carries trailing space.
func commentLines(text string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		if line == "" {
			lines[i] = "//"
		} else {
			lines[i] = "// " + line
		}
	}
	return strings.Join(lines, "\n")
}

func (d *definition) format() (code string) {
	switch d.objType {
	case objTypePrimitive:
		code = devutil.S(`
		{{.comment}}
		type {{.name}} {{.type}}
		`, "name", d.name, "type", d.typeName, "comment", d.comment())

		if d.enum != nil {
			code += "const ("
			for _, value := range d.enum {
				name := d.name + symbol(value)
				code += devutil.S(`
				{{.comment}}
				{{.name}} {{.type}} = "{{.value}}"
				`, "comment", commentLines(name+" enum const."+d.deprecatedParagraph()),
					"name", name, "type", d.name, "value", value)
			}
			code += ")\n"
		}

	case objTypeStruct:
		code = devutil.S(`
		{{.comment}}
		type {{.name}} struct {
		`, "name", d.name, "comment", d.comment())

		for _, prop := range d.props {
			tag := jsonTag(prop.originName, prop.optional)

			t := prop.typeName
			if prop.optional {
				switch prop.typeName {
				case "float64", "int":
					if !strings.Contains(prop.comment(), "(default: 0)") {
						t = "*" + t
					}
				}
			}

			code += devutil.S(`
			{{.comment}}
			{{.name}} {{.type}} {{.tag}}
			`, "comment", prop.comment(), "name", prop.name, "type", t, "tag", tag)
		}

		code += "}\n"

		if d.command {
			method := d.domain.name + "." + d.originName
			if d.returnValue {
				code += devutil.S(`
				// ProtoReq name.
				func (m {{.name}}) ProtoReq() string { return "{{.method}}" }

				// Call the request.
				func (m {{.name}}) Call(c Client) (*{{.name}}Result, error) {
					var res {{.name}}Result
					return &res, call(m.ProtoReq(), m, &res, c)
				}
				`, "name", d.name, "method", method)
			} else {
				code += devutil.S(`
				// ProtoReq name.
				func (m {{.name}}) ProtoReq() string { return "{{.method}}" }

				// Call sends the request.
				func (m {{.name}}) Call(c Client) error {
					return call(m.ProtoReq(), m, nil, c)
				}
				`, "name", d.name, "method", method)
			}
		}

		if d.cdpType == cdpTypeEvents {
			code += devutil.S(`
				// ProtoEvent name.
				func (evt {{.name}}) ProtoEvent() string {
					return "{{.event}}"
				}
			`, "name", d.name, "event", d.domain.name+"."+d.originName)
		}
	}

	return
}

func (d *definition) formatTests() (code string) {
	switch d.cdpType {
	case cdpTypeCommands:
		if !d.command {
			return ""
		}

		if d.returnValue {
			return devutil.S(`
				func (t T) {{.name}}() {
					c := &Client{}
					_, err := proto.{{.name}}{}.Call(c)
					t.Nil(err)
				}
				`, "name", d.name)
		}

		return devutil.S(`
			func (t T) {{.name}}() {
				c := &Client{}
				err := proto.{{.name}}{}.Call(c)
				t.Nil(err)
			}
			`, "name", d.name)

	case cdpTypeEvents:
		return devutil.S(`
		func (t T) {{.name}}() {
			e := proto.{{.name}}{}
			t.Regex("", e.ProtoEvent())
		}
		`, "name", d.name)
	}

	return ""
}

// cleanup removes every generated file of dir before the generation: the
// hand-written a_ files stay, every other Go file goes, so an entity the
// roll removed leaves no file behind.
func cleanup(dir string) error {
	list, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	for _, f := range list {
		if !f.IsDir() && !strings.HasPrefix(f.Name(), "a_") && strings.HasSuffix(f.Name(), ".go") {
			if err := os.Remove(filepath.Join(dir, f.Name())); err != nil {
				return err
			}
		}
	}
	return nil
}
